=== alepmendonca/PoltergeistFDT/resources/verificacoes-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/alepmendonca/PoltergeistFDT/blob/master/resources/verificacoes-schema.json",
    "type": "object",
    "properties": {
      "verificacao": {
        "type": "string"
      },
      "consulta": {
        "type": "string"
      },
      "funcao": {
        "type": "object",
        "properties": {
          "nome": {"type": "string"},
          "descricao": {"type": "string"}
        }
      },
      "manda_notificacao_ou_gera_infracao": {
        "type": "string"
      },
      "notificacao": {
        "type": "object",
        "properties": {
          "assunto": {
            "enum": [
              "Advertência para Escrituração Fiscal Digital (EFD)",
              "Crédito Acumulado",
              "Notificação de não lavratura de AIIM - Portaria CAT 115/2014",
              "Notificação para a prestação de informações e entrega de documentos fiscais",
              "Outros"
            ]
          },
          "titulo": {
            "type": "string"
          },
          "corpo": {
            "type": "string"
          },
          "anexo": {
            "type": "string"
          }
        },
        "required": [
          "titulo",
          "corpo"
        ],
        "additionalProperties": false
      },
      "infracoes": {
        "oneOf": [
          {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 1
          },
          {
            "type": "object",
            "minProperties": 1,
            "propertyNames": {
              "pattern": "^[IVX]+[a-z]"
            },
            "patternProperties": {
              "^[IVX][a-z]": {
                "type": "object",
                "minProperties": 1,
                "additionalProperties": false,
                "dependentRequired": {
                  "filtro_coluna": ["filtro"]
                },
                "properties": {
                  "relato": {
                    "type": "string"
                  },
                  "relatorio_circunstanciado": {
                    "type": "string"
                  },
                  "filtro": {"enum": ["positivo", "negativo"]},
                  "filtro_coluna": {"type": "string"},
                  "planilha_titulo": {"type": "string"},
                  "ttpa": {
                    "type": "array",
                    "minItens": 1,
                    "items": {"type": "number"}
                  },
                  "ordem": {
                    "enum": ["Não Sujeito a pg. 5%", "1% Vl das Operações", "Inexiste Eper. Prest. 70UF"]
                  },
                  "capitulacao": {
                    "type": "object",
                    "properties": {
                      "limpa": {
                        "type": "boolean"
                      },
                      "artigos": {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                          "type": "object",
                          "minProperties": 1,
                          "oneOf": [
                            {
                              "properties": {
                                "artigo": {
                                  "type": "string",
                                  "pattern": "\\d+[A-Z]*"
                                },
                                "inciso": {
                                  "type": "string",
                                  "pattern": "\\d+"
                                },
                                "alinea": {
                                  "type": "string",
                                  "pattern": "\\d+"
                                },
                                "paragrafo": {
                                  "type": "string",
                                  "pattern": "UN|\\d+"
                                },
                                "item": {
                                  "type": "string",
                                  "pattern": "\\d+"
                                },
                                "letra": {
                                  "type": "string",
                                  "pattern": "[A-Za-z]"
                                },
                                "junta": {
                                  "enum": ["Nenhum", "C/C", "E"]
                              	}
                              },
                              "required": ["artigo"],
                              "dependentRequired": {
                                "alinea": ["inciso"],
                                "item": ["paragrafo"],
                                "letra": ["paragrafo", "item"]
                              },
                              "additionalProperties": false
                            },
                            {
                              "properties": {
                                "especial": {
                                  "type": "string"
                                }
                              },
                              "required": ["especial"],
                              "additionalProperties": false
                            }
                          ]
                        }
                      }
                    },
                    "required": [
                      "artigos"
                    ],
                    "additionalProperties": false
                  },
                  "provas": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                      "type": "object",
                      "properties": {
                        "tipo": {
                          "enum": [
                            "listagem",
                            "LRE",
                            "LRS",
                            "LRI",
                            "LRAICMS",
                            "DFe",
                            "GIA-Extrato",
                            "GIA-Apuracao",
                            "GIA-OutrosDebitos",
                            "GIA-OutrosCreditos",
                            "EFD-Obrigatoriedade",
                            "EFD-Extrato"
                          ]
                        },
                        "descricao": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "tipo",
                        "descricao"
                      ],
                      "additionalProperties": false
                    }
                  }
                }
              }
            }
          }
        ]
      }
    },
  "oneOf": [
    {"required": ["verificacao", "consulta", "infracoes"]},
    {"required": ["verificacao", "funcao", "infracoes"]}
  ],
  "dependentSchemas": {
    "consulta": {
      "properties": {
        "consulta_detalhamento": {
          "type": "string"
        },
        "acerto_base": {
          "type": "string"
        },
        "planilha_nome": {
          "type": "string"
        }
      }
    }
  }
}

=== alepmendonca/PoltergeistFDT/resources/verificacoes/nao_exibicao_LRI.json
{
  "verificacao": "Não exibição de livro fiscal de inventário em EFD",
  "consulta": "WITH anos AS (\n\tSELECT dd::date AS referencia \n\tFROM generate_series(inicio_auditoria()::timestamp, (fim_auditoria() + INTERVAL '1 year')::timestamp, '1 year'::interval) AS dd\n), mes_inventario AS (\nSELECT make_date(date_part('year', anos.referencia)::int, 2, 1) AS referencia\nFROM anos\n), referencias_esperadas AS (\n\tSELECT mes_inventario.referencia\n\tFROM mes_inventario\n\tJOIN cadesp_regime ON mes_inventario.referencia BETWEEN cadesp_regime.inicio_regime AND COALESCE(cadesp_regime.fim_regime, now())\n\tWHERE cadesp_regime.ie = ie_auditoria() AND cadesp_regime.regime = 'RPA'\n)\nSELECT referencias_esperadas.referencia AS \"Referência\"\nFROM referencias_esperadas LEFT JOIN escrituracaofiscal ON referencias_esperadas.referencia = escrituracaofiscal.datainicial\nWHERE escrituracaofiscal.ie IS NULL\nORDER BY 1",
  "notificacao": {
    "titulo": "OSF <osf> -  Falta de entrega de Escrituração Fiscal Digital(EFD)",
    "corpo": "No Âmbito da Ordem de Serviço Fiscal <osf>, e em decorrência da não localização nas bases de dados desta Receita Estadual de Livro Registro de Inventário nas EFDs listadas a seguir, fica o contribuinte acima identificado NOTIFICADO a entregar a Escrituração Fiscal Digital d<periodo>, contendo especialmente as informações do Livro Fiscal Registro de Inventário referente ao ano anterior, sob pena de aplicação da penalidade prevista na Lei 6.374, art. 85, inciso V, alínea \"m\".<br><p><b>PRAZO PARA ATENDIMENTO</b>: 30 (trinta) dias, contados da ciência da notificação.<br><b>FORMA DE ATENDIMENTO</b>: Envio de EFDs pelo portal SPED Fiscal.<br><b>BASE LEGAL</b>: Art. 494 e 497 do RICMS (Aprovado pelo Decreto 45.490/00).</p>"
  },
  "infracoes": ["Vm-LRI"]
}

=== alepmendonca/PoltergeistFDT/resources/verificacoes/falta_LRI-SN.json
{
  "verificacao": "Falta de LRI - Simples Nacional",
  "funcao": {
  	"nome": "periodo_sn_lri",
  	"descricao": "Levanta os períodos de fiscalização em que o contribuinte esteve no regime Simples Nacional.\nResultado mostra os anos em que o contribuinte deveria apresentar LRI sem ser por EFD."
  },
  "infracoes": {
    "Vj-LRI": {
      "relato": "Deixou de exibir à autoridade fiscalizadora, no prazo cominado em notificação específica para tal fim, o Livro Fiscal de Registro de Inventário, referente a<periodoAAAA>, conforme se comprova pela notificação e demais documentos juntados no Anexo do item.",
	  "relatorio_circunstanciado": "a despeito de não ser obrigado a realizar Escrituração Fiscal Digital (EFD), enquanto sob o regime tributário Simples Nacional, cabe ao contribuinte adotar o Livro Registro de Inventário. Deixou o contribuinte de cumprir a exigência n<periodoAAAA>, pois não apresentou o Livro Registro de Inventário no prazo definido em notificação específica para tal fim.",
      "provas": [
      ]
    }
  },
  "notificacao": {
    "titulo": "OSF <osf> - Livro Fiscal Registro de Inventário",
    "corpo": "No âmbito da Ordem de Serviço Fiscal <osf>, fica o contribuinte acima identificado NOTIFICADO a apresentar o Livro Fiscal Registro de Inventário, referente a<periodoAAAA>.<br><p><b>PRAZO PARA ATENDIMENTO</b>: 10 (dez) dias, contados da ciência da notificação.<br><b>FORMA DE ATENDIMENTO</b>: Caso o livro fiscal seja físico, deve ser entregue na <delegacia>, aos cuidados do AFRE subscrevente, mediante agendamento pelo endereço eletrônico <email>; caso o livro fiscal esteja em formato eletrônico, definido na Portaria CAT 32/96, deve ser enviado ao endereço eletrônico <email>; caso o livro fiscal esteja em formato PDF, deve ser enviado por intermédio do SIPET - Sistema de Peticionamento Eletrônico, disciplinado pela Portaria CAT 83/20, que pode ser acessado através do endereço eletrônico https://www3.fazenda.sp.gov.br/sipet, utilizando a opção \"Comunicações\" -> \"Atendimento de notificação de fiscalização\".<br><b>BASE LEGAL</b>: Arts. 494 e 497 do RICMS (Aprovado pelo Decreto 45.490/00) c/c art. 63, II da Resolução CGSN 140/2018.</p>"
  }
}

=== alepmendonca/PoltergeistFDT/resources/verificacoes/nao_exibicao_livros.json
{
  "verificacao": "Não exibição de livro fiscal de apuração mensal em EFD",
  "consulta": "WITH referencias_esperadas AS (\n\tSELECT dd::date AS referencia \n\tFROM generate_series(inicio_auditoria()::timestamp, fim_auditoria()::timestamp, '1 month'::interval) AS dd\n\tJOIN cadesp_regime ON dd BETWEEN cadesp_regime.inicio_regime AND COALESCE(cadesp_regime.fim_regime, now())\n\tWHERE cadesp_regime.ie = ie_auditoria() AND cadesp_regime.regime = 'RPA'\n)\nSELECT referencias_esperadas.referencia AS \"Referência\"\nFROM referencias_esperadas LEFT JOIN escrituracaofiscal ON referencias_esperadas.referencia = escrituracaofiscal.datainicial\nWHERE escrituracaofiscal.ie IS NULL\nORDER BY 1",
  "notificacao": {
    "titulo": "OSF <osf> -  Falta de entrega de Escrituração Fiscal Digital(EFD)",
    "corpo": "No Âmbito da Ordem de Serviço Fiscal <osf>, e em decorrência da não localização nas bases de dados desta Receita Estadual de EFDs listadas a seguir, fica o contribuinte acima identificado NOTIFICADO a entregar a Escrituração Fiscal Digital d<periodo>, contendo especialmente as informações dos Livros Fiscais Registro de Entradas, Registro de Saídas e Apuração de ICMS, sob pena de aplicação da penalidade prevista na Lei 6.374, art. 85, inciso V, alínea \"m\".<br><p><b>PRAZO PARA ATENDIMENTO</b>: 30 (trinta) dias, contados da ciência da notificação.<br><b>FORMA DE ATENDIMENTO</b>: Envio de EFDs pelo portal SPED Fiscal.<br><b>BASE LEGAL</b>: Art. 494 e 497 do RICMS (Aprovado pelo Decreto 45.490/00).</p>"
  },
  "infracoes": ["Vm-LRS", "Vm-LRE", "Vm-LRAICMS"]
}

=== alepmendonca/PoltergeistFDT/resources/verificacoes/divergencias_rba_pgdas.json
{
  "verificacao": "Divergências RBA x PGDAS-D",
  "funcao": {
  	"nome": "verifica_divergencia_pgdas",
  	"descricao": "Levanta os meses nos quais o relatório do Launchpad \"SN-Receita_Bruta_Declarada_x_Apurada\" apontou divergências, durante o período em que o contribuinte estava no regime do Simples Nacional."
  },
  "notificacao": {
  	"titulo": "OSF <osf> - Divergências PGDAS-D e Receita Bruta Apurada",
  	"corpo": "No âmbito das verificações fiscais da Ordem de Serviço Fiscal <osf>, fica o contribuinte acima identificado NOTIFICADO a prestar informações que esclareçam as divergências identificadas, por meio de cruzamento de dados eletrônicos existentes nos bancos de dados desta Receita Estadual, entre a Receita Bruta Declarada em PGDAS-D n<periodoAAAA> e a Receita Bruta Apurada pelo Fisco, com base nos documentos fiscais eletrônicos emitidos pelo contribuinte, nos termos da planilha juntada.<br><p><b>PRAZO PARA ATENDIMENTO</b>: 10 (dez) dias, contados da ciência da notificação.<br><b>FORMA DE ATENDIMENTO</b>: Envio de declaração firmada por representante legal do contribuinte, digitalizada ou assinada digitalmente, para o endereço eletrônico <email><br><b>BASE LEGAL</b>: Art. 494 do RICMS (Aprovado pelo Decreto 45.490/00).</p>",
  	"anexo": "Divergências PGDAS-D"
  },
  "infracoes": []
}
